---
roles:
  - name: buluma.bootstrap
  - name: buluma.buildtools
  - name: buluma.core_dependencies
  - name: buluma.epel
  - name: robertdebock.python_pip
  - name: robertdebock.service
collections:
  - name: ansible.posix
